// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'infoWrap': string;
  'pictureWrap': string;
  'statItem': string;
  'statValue': string;
  'statWrap': string;
  'titleName': string;
  'wrap': string;
  'button': string;
  'popup': string;
  'info': string;
}
export const cssExports: CssExports;
export default cssExports;
