// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilities-box': string;
  'cardWrap': string;
  'id': string;
  'info': string;
  'label': string;
  'labels': string;
  'point': string;
  'points-box': string;
  'pokemonImage': string;
  'root': string;
  'stats-box': string;
  'stats-item': string;
  'stats-number': string;
  'stats-title': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
