// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeLink': string;
  'inner': string;
  'menuLink': string;
  'menuWrap': string;
  'nav_burger': string;
  'pokemonLogo': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
